# database:
#   system: TD1710
#   user: dbc

systems:
  CHBIT01: "tdgenf01prd.ezv.admin.ch"
  CHBIT02: "tdalba01dev.ezv.admin.ch"
  CHBIT07: "tdaare01prd.szp.admin.ch"
  CHBIT08: "tdthur01dev.szp.admin.ch"
  TD1720: "192.168.114.20"
  TD1710: "192.168.114.19"

tabs:
  CreateKeyfiles:
    type: "CreateKeyfiles"
    url: "/create_keyfiles"
    sql: ""
    template: "create_keyfiles.html"
    system: "TD1720"
    user: "dbc"
    jscript: "create_keyfiles.js"
    container_id: "create-keyfiles-container"

  DBSizes:
    type: "Chart"
    url: "/fetch_data?query=DBSizes"
    sql: |
      SELECT TRIM(DatabaseName) AS DatabaseName, SUM(CurrentPerm)/1024/1024 AS DatabaseSize_MB
      FROM DBC.AllSpace 
      WHERE DatabaseName NOT IN ('DBC')
      GROUP BY DatabaseName
      HAVING DatabaseSize_MB > 10 
      ORDER BY DatabaseSize_MB DESC    
    template: "db_sizes.html"
    system: "TD1720"
    user: "dbc"
    jscript: "db_sizes.js"
    container_id: "db-sizes-container"
    bar: "horizontal"  # Optionen: "horizontal" oder "vertical"

  UserSessions:
    type: "Table"
    url: "/fetch_data?query=UserSessions"
    sql: "SELECT * FROM DBC.SessionInfoV ORDER BY LogonTime DESC"
    template: "user_sessions.html"
    system: "TD1720"
    user: "dbc"
    jscript: "user_sessions.js"
    container_id: "user-sessions-container"

  ODILoads:
    type: "Table"
    url: "/fetch_data?query=ODILoads"
    sql: "SELECT LoadID, LoadName, StartTime, EndTime, Status FROM ODI.LoadHistory ORDER BY StartTime DESC"
    template: "odi_loads.html"
    system: "TD1720"
    user: "dbc"
    jscript: "odi_loads.js"
    container_id: "odi-loads-container"

  OPS-Shift(Early):
    type: "Dashboard"
    url: "/dashboard/OpsShiftEarly"
    template: "dboard.html"
    container_id: "dboard-OpsShiftEarly-container"
  Example(DashBoard):
    type: "Dashboard"
    url: "/dashboard/Example"
    template: "dboard.html"
    container_id: "dboard-Example-container"

dashboards:
  OpsShiftEarly:
    type: "DashBoard"
    template: "dboard.html"
    container_id: "dboard-OpsShiftEarly-container"
    rows:
      - rownbr: 1
        columns:
          - columnnbr: 2
            Chart: 
              ChartType:  "Table"  # ChartType als "Table" festlegen
            url: "/fetch_data?query=DashBoard"
            sql: |
              WITH 
              PRLA_Base AS (
                  SELECT 
                      DATE AS Datum,
                      CURRENT_TIMESTAMP(6) AS DatumUndZeitAktuell,
                      (CURRENT_TIMESTAMP(6) - CAST(PRLA.PRLA_StartDZ AS TIMESTAMP(6))) DAY(4) TO SECOND AS Differenz_Tag_Std_Min,
                      PRLA.PRLA_ProzessLauf,
                      PRLA.PROZ_Prozess,
                      PRLA.PRLA_StartDZ,
                      PRLA.PRLA_ProzessStatus,
                      PRLA.PRLA_Fehlernummer,
                      PROZ.PROZ_ProzessName,
                          CASE 
                      WHEN (CURRENT_TIMESTAMP(6) - PRLA.PRLA_StartDZ) DAY(4) TO SECOND > INTERVAL '16' HOUR THEN 'red'
                      WHEN (CURRENT_TIMESTAMP(6) - PRLA.PRLA_StartDZ) DAY(4) TO SECOND > INTERVAL '12' HOUR THEN 'yellow'
                      WHEN (CURRENT_TIMESTAMP(6) - PRLA.PRLA_StartDZ) DAY(4) TO SECOND > INTERVAL '510' MINUTE THEN 'green'
                      ELSE 'blue' -- Default if none of the conditions are met
                  END AS config_color
                  FROM DEVOPS_CONTROL.PRLA_ProzessLauf PRLA
                  INNER JOIN DEVOPS_CONTROL.PROZ_Prozess PROZ
                      ON PRLA.PROZ_Prozess = PROZ.PROZ_Prozess
                  WHERE PRLA.PROZ_Prozess NOT IN (31, 32)
              ),
              PRLA_Status2 AS (
                  SELECT * 
                  FROM PRLA_Base 
                  WHERE PRLA_ProzessStatus >= 2
              ),
              PRLA_Status3 AS (
                  SELECT * 
                  FROM PRLA_Base 
                  WHERE PRLA_ProzessStatus >= 3
                  QUALIFY ROW_NUMBER() OVER (ORDER BY PRLA_StartDZ DESC) = 1
              )
              SELECT 
                  drv1.PROZ_Prozessname
                  ,drv1.Differenz_Tag_Std_Min
                  ,drv1.config_color
                  ,drv1.PRLA_ProzessStatus
              FROM (
                  SELECT * 
                  FROM PRLA_Status2
                  UNION ALL
                  SELECT * 
                  FROM PRLA_Status3
              ) drv1
                ORDER BY 2 ASC;
            system: "TD1710"
            user: "dbc"

          - columnnbr: 1
            Chart: 
              ChartType: "Bar"
              orientation: "horizontal"  # Options für die Ausrichtung
              color: "blue"              # Optional: Farbe für Balken
              bar_width: 0.5             # Optional: Balkenbreite
            url: "/fetch_data?query=DashBoard"
            sql: |
              WITH 
              PRLA_Base AS (
                  SELECT 
                      DATE AS Datum,
                      CURRENT_TIMESTAMP(6) AS DatumUndZeitAktuell,
                      (CURRENT_TIMESTAMP(6) - CAST(PRLA.PRLA_StartDZ AS TIMESTAMP(6))) DAY(4) TO SECOND AS Differenz_Tag_Std_Min,
                      PRLA.PRLA_ProzessLauf,
                      PRLA.PROZ_Prozess,
                      PRLA.PRLA_StartDZ,
                      PRLA.PRLA_ProzessStatus,
                      PRLA.PRLA_Fehlernummer,
                      PROZ.PROZ_ProzessName,
                          CASE 
                      WHEN (CURRENT_TIMESTAMP(6) - PRLA.PRLA_StartDZ) DAY(4) TO SECOND > INTERVAL '16' HOUR THEN 'red'
                      WHEN (CURRENT_TIMESTAMP(6) - PRLA.PRLA_StartDZ) DAY(4) TO SECOND > INTERVAL '12' HOUR THEN 'yellow'
                      WHEN (CURRENT_TIMESTAMP(6) - PRLA.PRLA_StartDZ) DAY(4) TO SECOND > INTERVAL '510' MINUTE THEN 'green'
                      ELSE 'blue' -- Default if none of the conditions are met
                  END AS config_color
                  FROM DEVOPS_CONTROL.PRLA_ProzessLauf PRLA
                  INNER JOIN DEVOPS_CONTROL.PROZ_Prozess PROZ
                      ON PRLA.PROZ_Prozess = PROZ.PROZ_Prozess
                  WHERE PRLA.PROZ_Prozess NOT IN (31, 32)
              ),
              PRLA_Status2 AS (
                  SELECT * 
                  FROM PRLA_Base 
                  WHERE PRLA_ProzessStatus >= 2
              ),
              PRLA_Status3 AS (
                  SELECT * 
                  FROM PRLA_Base 
                  WHERE PRLA_ProzessStatus >= 3
                  QUALIFY ROW_NUMBER() OVER (ORDER BY PRLA_StartDZ DESC) = 1
              )
              SELECT 
                  drv1.PROZ_Prozessname
                  ,drv1.Differenz_Tag_Std_Min
                  ,drv1.config_color
                  ,drv1.PRLA_ProzessStatus
              FROM (
                  SELECT * 
                  FROM PRLA_Status2
                  UNION ALL
                  SELECT * 
                  FROM PRLA_Status3
              ) drv1
              UNION ALL SELECT * FROM (SELECT 
                'Current DatTime:'  || TO_CHAR(CURRENT_TIMESTAMP(6)) AS  PROZ_Prozessname
                ,INTERVAL '0 00:00:00.000000' DAY TO SECOND  Differenz_Tag_Std_Min
                ,'grey' config_color
                ,0 PRLA_ProzessStatus
                --,CURRENT_TIMESTAMP(6) AS PRLA_StartDZ 
                ) drv6
              ORDER BY 2 ASC;
            system: "TD1710"
            user: "dbc"
      - rownbr: 2  # Neue Zeile für eine Tabelle
        columns:
          - columnnbr: 1
            Chart: 
              ChartType: "Pie"
            url: "/fetch_data?query=DashBoard"
            sql: |
              SELECT TRIM(DatabaseName) AS DatabaseName, SUM(CurrentPerm)/1024/1024 AS DatabaseSize_MB
              FROM DBC.AllSpace WHERE DatabaseName NOT IN ('DBC')
              GROUP BY DatabaseName HAVING DatabaseSize_MB > 10 ORDER BY DatabaseSize_MB DESC
            system: "TD1720"
            user: "dbc"
          - columnnbr: 2
            Chart: 
              ChartType:  "Table"  # ChartType als "Table" festlegen
            url: "/fetch_data?query=DashBoard"
            sql: |
              SELECT TRIM(DatabaseName) AS DatabaseName, 
                    CreateTimeStamp, 
                    LastAccessTimeStamp
              FROM DBC.Databases
              WHERE CreateTimeStamp >  date '2023-10-01'
              ORDER BY LastAccessTimeStamp DESC
            system: "TD1720"
            user: "dbc"
      - rownbr: 3
        columns:
          - columnnbr: 1
            Chart: 
              ChartType: "Bar"
              orientation: "vertical"  # Options für die Ausrichtung
              color: "green"              # Optional: Farbe für Balken
              bar_width: 0.5             # Optional: Balkenbreite
            url: "/fetch_data?query=DashBoard"
            sql: |
              SELECT TRIM(DatabaseName) AS DatabaseName, SUM(CurrentPerm)/1024/1024 AS DatabaseSize_MB
              FROM DBC.AllSpace WHERE DatabaseName NOT IN ('DBC')
              GROUP BY DatabaseName HAVING DatabaseSize_MB > 10 ORDER BY DatabaseSize_MB DESC
            system: "TD1720"
            user: "dbc"
          - columnnbr: 2
            Chart: 
              ChartType:  "Pie"
            url: "/fetch_data?query=DashBoard"
            sql: |
              SELECT TRIM(DatabaseName) AS DatabaseName, SUM(CurrentPerm)/1024/1024 AS DatabaseSize_MB
              FROM DBC.AllSpace WHERE DatabaseName NOT IN ('DBC')
              GROUP BY DatabaseName HAVING DatabaseSize_MB > 10 ORDER BY DatabaseSize_MB DESC
            system: "TD1720"
            user: "dbc"
      - rownbr: 4  # Neue Zeile für eine Tabelle
        columns:
          - columnnbr: 1
            Chart: 
              ChartType:  "Table"  # ChartType als "Table" festlegen
            url: "/fetch_data?query=DashBoard"
            sql: |
              SELECT TRIM(DatabaseName) AS DatabaseName, 
                    CreateTimeStamp, 
                    LastAccessTimeStamp
              FROM DBC.Databases
              WHERE CreateTimeStamp >  date '2023-10-01'
              ORDER BY LastAccessTimeStamp DESC
            system: "TD1720"
            user: "dbc"            
  Example:
    type: "DashBoard"
    template: "dboard.html"
    container_id: "dboard-Exammple-container"
    rows:
      - rownbr: 1
        columns:
          - columnnbr: 2
            Chart: 
              ChartType: "Pie"
            url: "/fetch_data?query=DashBoard"
            sql: |
              SELECT TRIM(DatabaseName) AS DatabaseName, SUM(CurrentPerm)/1024/1024 AS DatabaseSize_MB
              FROM DBC.AllSpace WHERE DatabaseName NOT IN ('DBC')
              GROUP BY DatabaseName HAVING DatabaseSize_MB > 10 ORDER BY DatabaseSize_MB DESC
            system: "TD1720"
            user: "dbc"
          - columnnbr: 1
            Chart: 
              ChartType: "Bar"
              orientation: "horizontal"  # Options für die Ausrichtung
              color: "red"              # Optional: Farbe für Balken
              bar_width: 0.5             # Optional: Balkenbreite
            url: "/fetch_data?query=DashBoard"
            sql: |
              SELECT TRIM(DatabaseName) AS DatabaseName, SUM(CurrentPerm)/1024/1024 AS DatabaseSize_MB
              FROM DBC.AllSpace WHERE DatabaseName NOT IN ('DBC')
              GROUP BY DatabaseName HAVING DatabaseSize_MB > 10 ORDER BY DatabaseSize_MB DESC
            system: "TD1720"
            user: "dbc"
      - rownbr: 2  # Neue Zeile für eine Tabelle
        columns:
          - columnnbr: 1
            Chart: 
              ChartType:  "Table"  # ChartType als "Table" festlegen
            url: "/fetch_data?query=DashBoard"
            sql: |
              SELECT TRIM(DatabaseName) AS DatabaseName, 
                    CreateTimeStamp, 
                    LastAccessTimeStamp
              FROM DBC.Databases
              WHERE CreateTimeStamp >  date '2023-10-01'
              ORDER BY LastAccessTimeStamp DESC
            system: "TD1720"
            user: "dbc"
          - columnnbr: 2
            Chart: 
              ChartType:  "Table"  # ChartType als "Table" festlegen
            url: "/fetch_data?query=DashBoard"
            sql: |
              SELECT TRIM(DatabaseName) AS DatabaseName, 
                    CreateTimeStamp, 
                    LastAccessTimeStamp
              FROM DBC.Databases
              WHERE CreateTimeStamp >  date '2023-10-01'
              ORDER BY LastAccessTimeStamp DESC
            system: "TD1720"
            user: "dbc"
      - rownbr: 3
        columns:
          - columnnbr: 1
            Chart: 
              ChartType: "Bar"
              orientation: "vertical"  # Options für die Ausrichtung
              color: "green"              # Optional: Farbe für Balken
              bar_width: 0.5             # Optional: Balkenbreite
            url: "/fetch_data?query=DashBoard"
            sql: |
              SELECT TRIM(DatabaseName) AS DatabaseName, SUM(CurrentPerm)/1024/1024 AS DatabaseSize_MB
              FROM DBC.AllSpace WHERE DatabaseName NOT IN ('DBC')
              GROUP BY DatabaseName HAVING DatabaseSize_MB > 10 ORDER BY DatabaseSize_MB DESC
            system: "TD1720"
            user: "dbc"
          - columnnbr: 2
            Chart: 
              ChartType:  "Pie"
            url: "/fetch_data?query=DashBoard"
            sql: |
              SELECT TRIM(DatabaseName) AS DatabaseName, SUM(CurrentPerm)/1024/1024 AS DatabaseSize_MB
              FROM DBC.AllSpace WHERE DatabaseName NOT IN ('DBC')
              GROUP BY DatabaseName HAVING DatabaseSize_MB > 10 ORDER BY DatabaseSize_MB DESC
            system: "TD1720"
            user: "dbc"
      - rownbr: 4  # Neue Zeile für eine Tabelle
        columns:
          - columnnbr: 1
            Chart: 
              ChartType:  "Table"  # ChartType als "Table" festlegen
            url: "/fetch_data?query=DashBoard"
            sql: |
              SELECT TRIM(DatabaseName) AS DatabaseName, 
                    CreateTimeStamp, 
                    LastAccessTimeStamp
              FROM DBC.Databases
              WHERE CreateTimeStamp >  date '2023-10-01'
              ORDER BY LastAccessTimeStamp DESC
            system: "TD1720"
            user: "dbc"            